# Service identification
service_name = "Pulser Deposit Service"
version = "0.1.0"

# Network settings
network = "testnet"
esplora_url = "https://blockstream.info/testnet/api"
websocket_url = "wss://mempool.space/testnet/api/v1/ws"
fallback_esplora_url = "https://mempool.space/testnet/api"

# HTTP server settings
listening_address = "127.0.0.1"
listening_port = 8081

# File storage
data_dir = "data_lsp"
wallet_dir = "wallets"
event_log_dir = "events"

# Logging

log_level = "info"

# Bitcoin settings
lsp_pubkey = "tpubDG38QmNE5cgz7TdsxHd2riidQs8oFb1BVNCQxjyXbTygaLds5ecQQfiJZVpWkQLonaKxhiGCV1GJrHwV944SNF89dNoZftwH882L1u6Axcy" 
trustee_pubkey = "tpubDHMq987D4wpxPPDjNgzygAHENiTbQeFHgKeZ1Sy2SNCkTzMTRFMR71zNTCD38tuZpg1D8BHMHUYg8TF3C86K3CEpnmeYLA43S63oPn3swPa" 
min_confirmations = 1
channel_threshold_usd = 210.0
fee_percentage = 0.21

# Service integration
channel_service_url = "http://127.0.0.1:8082"
hedge_service_url = "http://127.0.0.1:8083"
api_key = "test_api_key"
request_timeout_secs = 30

# Webhook configuration (for webhook.rs)
webhook_enabled = true
webhook_url = "http://127.0.0.1:8084/webhook"
webhook_secret = "your_webhook_secret"
webhook_max_retries = 3
webhook_timeout_secs = 5
webhook_max_retry_time_secs = 120
webhook_retry_max_attempts = 3
webhook_base_backoff_ms = 500

# Monitor configuration (for monitor.rs)
monitor_min_check_interval_secs = 60  # Check each user every 1min
monitor_batch_size = 12

# Performance settings
sync_interval_secs = 300
hedge_update_interval_secs = 30
stagger_delay_secs = 5
max_sync_retries = 3
max_concurrent_users = 12
connection_timeout_secs = 60
user_scan_interval_secs = 300

# Role and node settings
role = "user"
ldk_address = "tb1qw508d6qejxtdg4y5r3zarvary0c5xw7kxpjzsx"

# Fee settings
max_fee_percent = 2.1

#Deribit
deribit_id = "kYlR7m6s"
deribit_secret = "i2ZQLPi6nlnwfQKCHVF0VqYEyC9jTxMBiPfWvSpk7t0"

# Withdrawals integration
deribit_testnet_address = "tb1q_deribit_testnet_dummy"
threshold_btc_address = "tb1q_threshold_dummy"
