# Service identification
service_name = "Pulser Deposit Service"
version = "0.1.0"

# Network settings - testnet only for now
network = "testnet"
esplora_url = "https://blockstream.info/testnet/api"

# HTTP server settings
listening_address = "127.0.0.1"
listening_port = 8081

# File storage
data_dir = "data"
wallet_dir = "wallets"
event_log_dir = "events"

# Logging - set to debug for testing
log_level = "debug"

# Bitcoin settings - replace with your actual keys
lsp_pubkey = "tpubDG38QmNE5cgz7TdsxHd2riidQs8oFb1BVNCQxjyXbTygaLds5ecQQfiJZVpWkQLonaKxhiGCV1GJrHwV944SNF89dNoZftwH882L1u6Axcy" 
trustee_pubkey = "tpubDHMq987D4wpxPPDjNgzygAHENiTbQeFHgKeZ1Sy2SNCkTzMTRFMR71zNTCD38tuZpg1D8BHMHUYg8TF3C86K3CEpnmeYLA43S63oPn3swPa" 
min_confirmations = 1 # Only 1 confirmation required for testing
channel_threshold_usd = 10.0 # Lower threshold for easier testing
fee_percentage = 0.21

# Service integration - use mock endpoints for testing
channel_service_url = "http://127.0.0.1:8082"
hedge_service_url = "http://127.0.0.1:8083"
api_key = "test_api_key"
request_timeout_secs = 30

# Service role - can be "user", "lsp", or "trustee"
role = "user"

# LDK node address for channel opening
ldk_address = "tb1qw508d6qejxtdg4y5r3zarvary0c5xw7kxpjzsx" # Testnet example address, replace with actual

# Maximum fee as a percentage of transaction amount
max_fee_percent = 5.0 # Higher for testnet as fees can be unpredictable
