[package]
name = "deposit-service"
version = "0.1.0"
edition = "2021"

[features]
user = []
lsp = []
trustee = []

[dependencies]
# BDK Wallet and dependencies - ensure all dependencies use compatible versions
bdk_wallet = "1.1.0"
bdk_file_store = "0.18.0"
bdk_chain = "0.11.0"
bdk_esplora = { version = "0.20.0", features = ["async-https"] }

# Bitcoin dependencies - stick with one compatible version
bitcoin = { version = "0.30.2", features = ["rand"] }

# For cryptography
sha2 = { version = "0.10", features = ["std"] }
hex = "0.4"
rand = "0.8"
base64 = "0.21"

# Async and HTTP/API
tokio = { version = "1", features = ["full"] }
actix-web = "4"
reqwest = { version = "0.11", features = ["json"] }

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Utilities
log = "0.4"
env_logger = "0.10"
thiserror = "1.0"
chrono = { version = "0.4", features = ["serde"] }
structopt = "0.3"
toml = "0.7"

# Common library
common = { path = "../common" }
